CREATE TABLE `distribution` (
  `DistributionID` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '派单ID',
  `AdminID` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '管理员ID',
  `Distributer` varchar(200) NOT NULL DEFAULT '' COMMENT '派单人',
  `Channel` tinyint(3) DEFAULT '1' COMMENT '渠道:1内部,2外部',
  `Platform` tinyint(3) DEFAULT '1' COMMENT '平台:1公众号,2服务号,3微博,4抖音',
  `FanNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '总粉丝数',
  `ObjectName` varchar(500) NOT NULL DEFAULT '' COMMENT '派单对象名,公众号服务号名称,微博抖音网红',
  `Devices` varchar(1000) NOT NULL DEFAULT '' COMMENT '个号设备编号串',
  `WeixinIDs` varchar(1000) NOT NULL DEFAULT '' COMMENT '个号设备对应当时的微信号ID串',
  `Price` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '价格',
  `TotalFriendNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '个号进粉总数',
  `2HFriendNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '2H进粉数',
  `24HFriendNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '24H进粉数',
  `48HFriendNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '48H进粉数',
  `72HFriendNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '72H进粉数',
  `48HOrderNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '48H出单量',
  `48HOrderAmount` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '48H销售额',
  `TotalOrderNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '总出单量',
  `TotalOrderAmount` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '总销售额',
  `24HIncomePerFriend` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '单粉24H收益',
  `15DIncomePerFriend` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '单粉15天收益',
  `30DIncomePerFriend` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '单粉30天收益',
  `ArticleCategoryID` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '文章类型',
  `ArticleViewNum` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '文章阅读数',
  `ArticlePosition` varchar(100) NOT NULL DEFAULT '' COMMENT '文章位置',
  `ArticleTitle` varchar(500) NOT NULL DEFAULT '' COMMENT '文章标题',
  `ArticleUrl` varchar(255) NOT NULL DEFAULT '' COMMENT '文章链接',
  `ViewNumGetTime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '阅读数获取时间,间隔一小时让客户端获取一次',
  `SendTime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '派单推送时间',
  PRIMARY KEY (`DistributionID`),
  KEY `ArticleUrl` (`ArticleUrl`),
  KEY `SendTime` (`SendTime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='派单表';