<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<form action="https://wxgroup.duomai.com/baidu/audio" method="post"
      enctype="multipart/form-data">
    <label for="file">Filename:</label>
    <input type="file" name="audio" id="file" />
    <br />
    <input type="submit" name="submit" value="Submit" />
</form>
<!--
<div>
    <dl>
        <dt>任务</dt>
        <dd><a href="/task/run" target="_blank">执行</a></dd>
    </dl>
    <dl>
        <dt>群</dt>
        <dd><a href="/group/create-task/?Name=测试" target="_blank">创建群</a></dd>
        <dd><a href="/group/update-task/?IsAll=1" target="_blank">更新群</a></dd>
    </dl>
    <dl>
        <dt>朋友圈</dt>
        <dd><a href="/message_friendgroup/send/?Type=TEXT&Text=这是一段纯文字" target="_blank">纯文字</a></dd>
        <dd><a href="/message_friendgroup/send/?Type=TEXT&Media=https://wx2.sinaimg.cn/mw690/00685TFIly1fr7dijr64ej30j60j6di1.jpg" target="_blank">纯图片</a></dd>
        <dd><a href="/message_friendgroup/send/?Type=TEXT&Text=这是一段图文&Media=https://wx2.sinaimg.cn/mw690/00685TFIly1fr7dijr64ej30j60j6di1.jpg" target="_blank">图片+文字</a></dd>
        <dd><a href="/message_friendgroup/send/?Type=TEXT&Media=https://www.baidu.com" target="_blank">纯链接</a></dd>
        <dd><a href="/message_friendgroup/send/?Type=TEXT&Text=这是一段链接+文字&Media=https://www.baidu.com" target="_blank">链接+文字</a></dd>
    </dl>
</div>
-->